In [5]:
import kaggle
kaggle.api.authenticate()
kaggle.api.dataset_download_files(
    'fredericobreno/play-tennis',
    unzip =True,
    path = '.'
    
)

Dataset URL: https://www.kaggle.com/datasets/fredericobreno/play-tennis

In [1]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv('NAIVE-BAYES\play_tennis.csv')

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\NIKHI\AppData\Local\Temp\ipykernel_5476\2139671835.py:1: SyntaxWarning: invalid escape sequence '\p'
  df = pd.read_csv('NAIVE-BAYES\play_tennis.csv')

In [8]:
df

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [10]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [11]:
py = 9/14
pn = 5/14

In [12]:
pd.crosstab(df['play'], df['outlook'])

outlook  Overcast  Rain  Sunny
play
No              0     2      3
Yes             4     3      2

In [ ]:
pon =0
poy = 4/9
prn = 2/5
pry = 3/9
psn= 3/5
psy =2/9

### GaussianNB → Continuous numerical features (most common)
### MultinomialNB → Count data (e.g., text classification)
### BernoulliNB → Binary features (0/1)
### CategoricalNB → Categorical features

In [ ]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train, y_train)
y_pred = nb.predict(X_test)
y_prob = nb.predict_proba(X_test)