In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df  = pd.read_csv(r'train.csv')

In [3]:
df.head()

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,48,0:0,0.048804,NaN,1,Not Allowed,No,NaN,NaN
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,NaN,Rainy
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy

In [4]:
df['geohash'].nunique()

1249

In [5]:
import pygeohash as pgh

lat, lon = pgh.decode("qp02zq")

print(lat, lon)

-5.45745849609375 90.6756591796875

In [6]:
!pip install pygeohash

Defaulting to user installation because normal site-packages is not writeable
Collecting pygeohash
  Downloading pygeohash-3.3.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Downloading pygeohash-3.3.0-cp314-cp314-win_amd64.whl (36 kB)
Installing collected packages: pygeohash
Successfully installed pygeohash-3.3.0

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
df2 = pd.read_csv(r'titanic.csv')

In [8]:
df2

    Cabin            Ticket number  Survived
0     NaN         A/5 21171      5         0
1     C85          PC 17599      3         1
2     NaN  STON/O2. 3101282      6         1
3    C123            113803      3         1
4     NaN            373450      A         0
..    ...               ...    ...       ...
886   NaN            211536      3         0
887   B42            112053      3         1
888   NaN        W./C. 6607      1         0
889  C148            111369      2         1
890   NaN            370376      3         0

[891 rows x 4 columns]

In [9]:
df2['number'].dtype

dtype('O')

In [10]:
df2['number'].value_counts()

number
A    139
6    131
1    129
2    126
4    126
5    123
3    117
Name: count, dtype: int64

####extract numerical part

In [11]:
df2['number_numerical']= pd.to_numeric(df2['number'],errors= 'coerce', downcast= 'integer')
df2['number_numerical']

0      5.0
1      3.0
2      6.0
3      3.0
4      NaN
      ...
886    3.0
887    3.0
888    1.0
889    2.0
890    3.0
Name: number_numerical, Length: 891, dtype: float64

In [12]:
df2['number_categorical']= np.where(df2['number_numerical'].isnull(), df2['number'], np.nan)

In [13]:
df2['Ticket'].dtype

dtype('O')

In [14]:
df2['Cabin'].dtype

dtype('O')

### second type

In [15]:
df2['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64', 'E24', 'C90', 'C45', 'E8', 'B101', 'D45', 'C46', 'D30',
       'E121', 'D11', 'E77', 'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36',
       'B102', 'B69', 'E49', 'C47', 'D28', 'E17', 'A24', 'C50', 'B42',
       'C148'], dtype=object)

In [16]:
# you have to analyze what col is representing and then you have to deparate u usign dedired function