In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\MACHINE LEARNING ADVANCE\DATA GATHERING\KAGGLE-WORKING\dataset\SVMtrain.csv')

In [4]:
df.sample(6)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
123,125,0,1,Male,54.0,0,1,77.2875,3
558,560,1,3,female,36.0,1,0,17.4000,3
161,163,0,3,Male,26.0,0,0,7.7750,3
571,573,1,1,Male,36.0,0,0,26.3875,3
537,539,0,3,Male,60.0,0,0,14.5000,3
849,852,0,3,Male,74.0,0,0,7.7750,3

In [6]:
df.shape

(889, 9)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  889 non-null    int64
 1   Survived     889 non-null    int64
 2   Pclass       889 non-null    int64
 3   Sex          889 non-null    str
 4   Age          889 non-null    float64
 5   SibSp        889 non-null    int64
 6   Parch        889 non-null    int64
 7   Fare         889 non-null    float64
 8   Embarked     889 non-null    int64
dtypes: float64(2), int64(6), str(1)
memory usage: 62.6 KB

# are there any missing values

In [9]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

# how does data look mathematically

In [10]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Embarked
count,889.000000,889.000000,889.000000,889.000000,889.000000,889.000000,889.000000,889.000000
mean,446.000000,0.382452,2.311586,35.686355,0.524184,0.382452,32.096681,2.535433
std,256.998173,0.486260,0.834700,17.756733,1.103705,0.806761,49.697504,0.792088
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000,1.000000
25%,224.000000,0.000000,2.000000,22.000000,0.000000,0.000000,7.895800,2.000000
50%,446.000000,0.000000,3.000000,32.000000,0.000000,0.000000,14.454200,3.000000
75%,668.000000,1.000000,3.000000,54.000000,1.000000,0.000000,31.000000,3.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200,3.000000

# are there any duplicate values

In [18]:
df.duplicated().sum()
df = df.drop_duplicates()
df.shape

(889, 9)

# how is the correlation between cols

In [12]:
df.corr(numeric_only=True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Embarked
PassengerId,1.000000,-0.005028,-0.035330,0.008341,-0.057686,-0.001657,0.012703,0.013166
Survived,-0.005028,1.000000,-0.335549,-0.116558,-0.034040,0.083151,0.255290,-0.169718
Pclass,-0.035330,-0.335549,1.000000,-0.122449,0.081656,0.016824,-0.548193,0.164681
Age,0.008341,-0.116558,-0.122449,1.000000,-0.156777,-0.215191,-0.003307,-0.124894
SibSp,-0.057686,-0.034040,0.081656,-0.156777,1.000000,0.414542,0.160887,0.068900
Parch,-0.001657,0.083151,0.016824,-0.215191,0.414542,1.000000,0.217532,0.040449
Fare,0.012703,0.255290,-0.548193,-0.003307,0.160887,0.217532,1.000000,-0.226311
Embarked,0.013166,-0.169718,0.164681,-0.124894,0.068900,0.040449,-0.226311,1.000000

# check col names

In [13]:
df.columns.tolist()

['PassengerId',
 'Survived',
 'Pclass',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Fare',
 'Embarked']

### check class balance

In [ ]:
df['PassengerId'].value_counts()
# how many times each class appears

PassengerId
1      1
2      1
3      1
4      1
5      1
      ..
887    1
888    1
889    1
890    1
891    1
Name: count, Length: 889, dtype: int64

### Handle duplicates if any found

In [17]:
numerical_cols = df.select_dtypes(include = ['int64','float64']).columns.tolist()
categorical_cols =df.select_dtypes(include = ['object','category']).columns.tolist()
print("Numerical:", numerical_cols)
print("Categorical:", categorical_cols)

Numerical: ['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']
Categorical: ['Sex']

C:\Users\NIKHI\AppData\Local\Temp\ipykernel_17084\2766807769.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols =df.select_dtypes(include = ['object','category']).columns.tolist()

### handle missing values if any found

In [21]:
# Either drop
# df = df.dropna()

# Or fill
# df.fillna(df.mean(), inplace=True)  # for numerical
df.fillna(df.mode()[0], inplace=True)  # for categorical

KeyError: 0